steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ultra-zenith-410711/gcp-test-app:latest', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ultra-zenith-410711/gcp-test-app:latest']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'gcp-test-app'
  - '--image'
  - 'gcr.io/ultra-zenith-410711/gcp-test-app:latest'
  - '--region'
  - 'europe-west1'
images:
  - 'gcr.io/ultra-zenith-410711/gcp-test-app:latest'